/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "circle_test.asn1"
 * 	`asn1c -D output -pdu=auto -no-gen-OER -no-gen-example`
 */

#ifndef	_Circle_H_
#define	_Circle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Circle */
typedef struct Circle {
	long	 position_x;
	long	 position_y;
	unsigned long	 radius;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Circle_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_radius_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Circle;

#ifdef __cplusplus
}
#endif

#endif	/* _Circle_H_ */
#include <asn_internal.h>
